import { mergeSymbolSpec } from './schema.ts'
import type { SymbolSpec } from './types.ts'

/** Seed registry — extend via mergeSymbolSpec; all entries mockOnly. */
export const SYMBOL_SPEC_REGISTRY: Record<string, SymbolSpec> = {
  BTCUSDT: mergeSymbolSpec({
    symbol: 'BTCUSDT',
    displayName: 'BTC/USDT',
    marketType: 'coin',
    tickSize: 0.5,
    lotSize: 0.001,
    priceDecimals: 1,
    qtyDecimals: 4,
    contractMultiplier: 1,
    currency: 'USDT',
    hedgeEnabled: true,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: true,
  }),
  ETHUSDT: mergeSymbolSpec({
    symbol: 'ETHUSDT',
    displayName: 'ETH/USDT',
    marketType: 'coin',
    tickSize: 0.05,
    lotSize: 0.001,
    priceDecimals: 2,
    qtyDecimals: 4,
    contractMultiplier: 1,
    currency: 'USDT',
    hedgeEnabled: true,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: true,
  }),
  SOLUSDT: mergeSymbolSpec({
    symbol: 'SOLUSDT',
    displayName: 'SOL/USDT',
    marketType: 'coin',
    tickSize: 0.01,
    lotSize: 0.01,
    priceDecimals: 2,
    qtyDecimals: 2,
    contractMultiplier: 1,
    currency: 'USDT',
    hedgeEnabled: true,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: true,
  }),
  AAPL: mergeSymbolSpec({
    symbol: 'AAPL',
    displayName: 'Apple Inc',
    marketType: 'us_stock',
    tickSize: 0.01,
    lotSize: 1,
    priceDecimals: 2,
    qtyDecimals: 0,
    contractMultiplier: 1,
    currency: 'USD',
    hedgeEnabled: false,
    mitEnabled: false,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: false,
  }),
  '005930': mergeSymbolSpec({
    symbol: '005930',
    displayName: '삼성전자',
    marketType: 'kr_stock',
    tickSize: 100,
    lotSize: 1,
    priceDecimals: 0,
    qtyDecimals: 0,
    contractMultiplier: 1,
    currency: 'KRW',
    hedgeEnabled: false,
    mitEnabled: false,
    stopEnabled: true,
    shortEnabled: false,
    leverageEnabled: false,
  }),
  ESZ6: mergeSymbolSpec({
    symbol: 'ESZ6',
    displayName: 'E-mini S&P',
    marketType: 'overseas_future',
    tickSize: 0.25,
    lotSize: 1,
    priceDecimals: 2,
    qtyDecimals: 0,
    contractMultiplier: 50,
    currency: 'USD',
    hedgeEnabled: false,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: true,
  }),
  KOSPI200F: mergeSymbolSpec({
    symbol: 'KOSPI200F',
    displayName: 'KOSPI200 선물',
    marketType: 'kr_future',
    tickSize: 0.05,
    lotSize: 1,
    priceDecimals: 2,
    qtyDecimals: 0,
    contractMultiplier: 250_000,
    currency: 'KRW',
    hedgeEnabled: false,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: true,
  }),
  BTC_97000_C: mergeSymbolSpec({
    symbol: 'BTC_97000_C',
    displayName: 'BTC 97000 Call',
    marketType: 'option',
    tickSize: 0.5,
    lotSize: 0.01,
    priceDecimals: 1,
    qtyDecimals: 2,
    contractMultiplier: 1,
    currency: 'USDT',
    hedgeEnabled: false,
    mitEnabled: true,
    stopEnabled: true,
    shortEnabled: true,
    leverageEnabled: false,
  }),
}
